//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_siugEntities : DbContext
    {
        public bd_siugEntities()
            : base("name=bd_siugEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_access> tb_access { get; set; }
        public virtual DbSet<tb_bill> tb_bill { get; set; }
        public virtual DbSet<tb_category> tb_category { get; set; }
        public virtual DbSet<tb_clients> tb_clients { get; set; }
        public virtual DbSet<tb_profile> tb_profile { get; set; }
        public virtual DbSet<tb_provider> tb_provider { get; set; }
        public virtual DbSet<tb_role> tb_role { get; set; }
        public virtual DbSet<tb_role_user> tb_role_user { get; set; }
        public virtual DbSet<tb_sale> tb_sale { get; set; }
        public virtual DbSet<tb_sale_detail> tb_sale_detail { get; set; }
        public virtual DbSet<tb_state> tb_state { get; set; }
        public virtual DbSet<tb_stock> tb_stock { get; set; }
        public virtual DbSet<tb_users> tb_users { get; set; }
    }
}
