//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_access
    {
        public long acc_id { get; set; }
        public long acc_us_id { get; set; }
        public Nullable<System.DateTime> acc_date { get; set; }
        public Nullable<System.DateTime> acc_final_date { get; set; }
    
        public virtual tb_users tb_users { get; set; }
    }
}
