//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bill
    {
        public long bil_id { get; set; }
        public System.DateTime bil_date { get; set; }
        public Nullable<long> bil_state { get; set; }
        public decimal bil_total { get; set; }
        public long bil_sal_id { get; set; }
    
        public virtual tb_state tb_state { get; set; }
        public virtual tb_sale tb_sale { get; set; }
    }
}
