//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_clients()
        {
            this.tb_sale = new HashSet<tb_sale>();
        }
    
        public long cli_id { get; set; }
        public string cli_nit { get; set; }
        public string cli_name_company { get; set; }
        public string cli_name_contact { get; set; }
        public string cli_last_name_contact { get; set; }
        public string cli_phone { get; set; }
        public string cli_cel_phone { get; set; }
        public string cli_email { get; set; }
        public System.DateTime cli_date { get; set; }
        public long cli_state { get; set; }
    
        public virtual tb_state tb_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sale> tb_sale { get; set; }
    }
}
