//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sale_detail
    {
        public long sade_id { get; set; }
        public long sade_sale_id { get; set; }
        public long sade_stock_id { get; set; }
        public long sade_quantity { get; set; }
        public decimal sade_subtotal { get; set; }
    
        public virtual tb_sale tb_sale { get; set; }
        public virtual tb_stock tb_stock { get; set; }
    }
}
