//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_users()
        {
            this.tb_access = new HashSet<tb_access>();
            this.tb_role_user = new HashSet<tb_role_user>();
            this.tb_sale = new HashSet<tb_sale>();
        }
    
        public long us_id { get; set; }
        public string us_name { get; set; }
        public string us_lastname { get; set; }
        public string us_phone { get; set; }
        public string us_email { get; set; }
        public string us_pass { get; set; }
        public long us_cityId { get; set; }
        public System.DateTime us_createDate { get; set; }
        public long us_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_access> tb_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_role_user> tb_role_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sale> tb_sale { get; set; }
        public virtual tb_state tb_state { get; set; }
    }
}
