//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testi2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.tb_access = new HashSet<tb_access>();
            this.tb_role_user = new HashSet<tb_role_user>();
            this.tb_sale = new HashSet<tb_sale>();
        }
    
        public long userId { get; set; }
        public string userName { get; set; }
        public string userLastNamel { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userPass { get; set; }
        public long userCityId { get; set; }
        public System.DateTime userCreateDate { get; set; }
        public long userState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_access> tb_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_role_user> tb_role_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sale> tb_sale { get; set; }
        public virtual tb_state tb_state { get; set; }
    }
}
